CREATE TABLE IF NOT EXISTS users (
    id       VARCHAR(36)  PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(60)  NOT NULL,
    handler  VARCHAR(50)  NOT NULL UNIQUE
);
